version: '3.4'

services:
  nginx:
    build: 
        context: .
        dockerfile: docker/Nginx.Dockerfile
    ports:
      - 80:80
    links:
      - fpm
    volumes:
      - ./:/var/www/laravel-dockerdocker
  
  fpm:
    build: 
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/laravel-docker
    links:
      - mysql
    
  mysql:
    image: mysql:8.0
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
